# Generated by Django 5.2 on 2025-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
