# Generated by Django 5.2 on 2025-04-29 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0003_linkedinmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedinmessage',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='linkedinaccount',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='linkedinaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='linkedin_message_id',
        ),
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='linkedinaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-29 10:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='li_at_cookie',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='linkedinaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkedinmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
