# Generated by Django 5.2 on 2025-04-29 11:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_rename_body_linkedinmessage_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='account',
        ),
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='conversation_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='sender',
            field=models.CharField(default='unknown sender', max_length=255),
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='text',
            field=models.TextField(default='no text'),
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkedinmessage',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='LinkedInAccount',
        ),
    ]
