# Generated by Django 5.2 on 2025-04-29 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0006_linkedinaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedinaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='linkedinmessage',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterField(
            model_name='linkedinmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='linkedinaccount',
            unique_together={('user', 'email')},
        ),
    ]
